redis-ha:
  enabled: true

controller:
  replicas: 1
  serviceAccount:
    annotations:

server:
  replicas: 2
  serviceAccount:
    annotations:

repoServer:
  replicas: 2
  serviceAccount:
    name: hacky-argocd-repo-server
    annotations:
      iam.gke.io/gcp-service-account: hacky-automation@wj-labs-407316.iam.gserviceaccount.com
  image:
    repository: javierlga/argocd
    tag: v2.9.3-1
    imagePullPolicy: Always
  containerSecurityContext:
    runAsUser: 999
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL

applicationSet:
  replicas: 2
