global:
  enabled: true
  name: consul
  datacenter: dc1
  image: "hashicorp/consul:1.16.0"
  acls:
    manageSystemACLs: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

server:
  enabled: true
  replicas: 1

connectInject:
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: true

ui:
  enabled: true
  service:
    type: LoadBalancer
