global:
  enabled: true
  name: consul
  datacenter: dc1
  acls:
    manageSystemACLs: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

server:
  enabled: true
  replicas: 1

connectInject:
  transparentProxy:
    defaultEnabled: false
  enabled: true
  default: false
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer

ui:
  enabled: true
  service:
    type: LoadBalancer
